name: menu
description: Menu App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  auto_animated: ^3.1.0
  brasil_fields: ^1.10.0
  cupertino_icons: ^1.0.2
  diacritic: ^0.1.3
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  go_router: ^6.0.1
  google_fonts: ^4.0.1
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
