name: menu
description: Menu App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  auto_animated: ^3.1.0
  brasil_fields: ^1.11.0
  cupertino_icons: ^1.0.5
  diacritic: ^0.1.3
  dio: ^5.1.1
  either_dart: ^0.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^4.0.3
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
